import unittest
from src.schemas.exercise_schemas import EXERCISE_MODELS, MCQImageExercise, ListeningComprehensionExercise
from pydantic import ValidationError

class TestESLStructure(unittest.TestCase):
    
    def test_mcq_image_with_audio(self):
        """Test MCQ Image structure with full audio support (Instruction + Options)."""
        data = {
            "content": {
                "question": "Which animal says Meow?",
                "question_audio": "http://s3/audio/q1.mp3",
                "options": [
                    {
                        "id": "opt1", 
                        "image_url": "http://s3/img/cat.png", 
                        "caption": "Cat",
                        "audio_url": "http://s3/audio/cat.mp3"
                    },
                    {
                        "id": "opt2", 
                        "image_url": "http://s3/img/dog.png", 
                        "caption": "Dog",
                        "audio_url": "http://s3/audio/dog.mp3"
                    }
                ]
            },
            "grading": {"answer_key": 0},
            "generation": {"options_prompts": ["A cat", "A dog"]}
        }
        
        # Validation
        model = MCQImageExercise(**data)
        self.assertEqual(model.content.question_audio, "http://s3/audio/q1.mp3")
        self.assertEqual(model.content.options[0].audio_url, "http://s3/audio/cat.mp3")

    def test_listening_comprehension_core_audio(self):
        """Test Listening Comprehension with core audio file."""
        data = {
            "content": {
                "instruction": "Listen to the conversation.",
                "instruction_audio": "http://s3/audio/instr.mp3",
                "audio_url": "http://s3/audio/dialogue.mp3",
                "question": "Where are they?",
                "options": ["Park", "School"]
            },
            "grading": {"answer_key": 0},
            "generation": {"audio_script": "A: Hi! B: Hello!"}
        }
        
        model = ListeningComprehensionExercise(**data)
        self.assertEqual(model.content.audio_url, "http://s3/audio/dialogue.mp3")
        self.assertEqual(model.content.instruction_audio, "http://s3/audio/instr.mp3")

    def test_asset_backfilling_logic(self):
        """Simulate the Controller filling in audio URLs via path."""
        # Initial state from LLM (audio_url is None)
        raw_data = {
            "content": {
                "question": "Select the apple.",
                "options": [
                    {"id": "1", "image_url": "", "caption": "Apple"},
                    {"id": "2", "image_url": "", "caption": "Banana"}
                ]
            },
            "grading": {"answer_key": 0},
            "generation": {}
        }
        
        # Asset Specs generated by LLM or Controller
        asset_specs = [
            {"target_path": "content.question_audio", "url": "http://gen/q.mp3"},
            {"target_path": "content.options[0].audio_url", "url": "http://gen/apple.mp3"},
            {"target_path": "content.options[0].image_url", "url": "http://gen/apple.png"}
        ]
        
        # Simulation of Assembly
        # We need to traverse the dict and set values
        import re
        
        def set_value_by_path(obj, path, value):
            parts = path.split('.')
            current = obj
            for i, part in enumerate(parts[:-1]):
                # Handle array index like options[0]
                match = re.match(r'(\w+)\[(\d+)\]', part)
                if match:
                    key, idx = match.groups()
                    current = current[key][int(idx)]
                else:
                    current = current[part]
            
            last_part = parts[-1]
            match = re.match(r'(\w+)\[(\d+)\]', last_part)
            if match:
                key, idx = match.groups()
                current[key][int(idx)] = value
            else:
                current[last_part] = value

        # Apply updates
        for spec in asset_specs:
            set_value_by_path(raw_data, spec["target_path"], spec["url"])
            
        # Verify with Pydantic Model
        model = MCQImageExercise(**raw_data)
        self.assertEqual(model.content.question_audio, "http://gen/q.mp3")
        self.assertEqual(model.content.options[0].audio_url, "http://gen/apple.mp3")
        self.assertEqual(model.content.options[0].image_url, "http://gen/apple.png")
        self.assertIsNone(model.content.options[1].audio_url)

if __name__ == '__main__':
    unittest.main()
